### PR TITLE
Fix syntax error for Ruby <= 2.1

### PR DESCRIPTION
**Pull request by yogeshjain999**

### CODE REVIEW

**Comment by seuros** [comment]
Most of the other gems require Ruby 2.2+, i dont think we should support that old syntax.
cc @emaglio

**Comment by yogeshjain999** [comment]
@seuros well, activity supports 2.1.0, so this needs too.

**Comment by seuros** [comment]
@yogeshjain999 Ruby 2.1 is EOL for 2 years and has security issues. Whoever need to use this, will have to use a recent stack. Also updating to 2.3 is trivial.
We can bump min support to 2.2 in activity.

**Comment by apotonick** [comment]
We might just as well drop 2.1 - I have no compelling reason why `activity` supports 2.1.

**Comment by emaglio** [comment]
I think the support to old ruby version is basically just to make Travis to pass for most of the gems - I mean 2.1 and 2.2 don't even install on my machine so yeah for me we can support from 2.3 :+1: 
So maybe this PR would simply be removing the old ruby versions in Travis

**Comment by yogeshjain999** [comment]
@emaglio Actually, `.travis.yml` doesn't have old Ruby versions and tests doesn't fail because of this.
I think @apotonick was using 2.1 somewhere ? Otherwise we can close this PR.

**Comment by emaglio** [comment]
@yogeshjain999 yeah I meant in the general in other PRs didn't check about this one - I'll let you guys decide what needs to be done :+1:

**Comment by apotonick** [comment]
Let's simply drop 2.1?

**Pull request closed without merging**
